// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAttachmentResponse = z.object({
    id: z.string().uuid(),
    guide_id: z.string().uuid(),
    filename: z.string(),
    content_type: z.string(),
    byte_size: z.number().int(),
    uploaded_by: z.string().uuid(),
    created_at: z.string().datetime()
});

export const zAuditLogEntry = z.object({
    id: z.string().uuid(),
    occurred_at: z.string().datetime(),
    actor_type: z.string(),
    actor_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    action: z.string(),
    target_type: z.union([
        z.string(),
        z.null()
    ]),
    target_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    household_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    detail: z.object({}),
    request_id: z.union([
        z.string(),
        z.null()
    ])
});

export const zAuthorizeRequest = z.object({
    consent_types: z.array(z.string()).min(1)
});

export const zAuthorizeResponse = z.object({
    authorize_url: z.string()
});

export const zAutoAcceptRuleCreate = z.object({
    template_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    max_price: z.number().int().gte(1).lte(100000)
});

export const zAutoAcceptRuleResponse = z.object({
    id: z.string().uuid(),
    member_id: z.string().uuid(),
    template_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    max_price: z.number().int(),
    active: z.boolean()
});

export const zBalanceResponse = z.object({
    balance: z.number().int()
});

export const zBannerCreate = z.object({
    message: z.string().min(1).max(500),
    level: z.enum([
        'info',
        'warning'
    ]).optional(),
    starts_at: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    ends_at: z.union([
        z.string().datetime(),
        z.null()
    ]).optional()
});

export const zBannerResponse = z.object({
    id: z.string().uuid(),
    message: z.string(),
    level: z.enum([
        'info',
        'warning'
    ]),
    is_active: z.boolean(),
    starts_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    ends_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    created_at: z.string().datetime()
});

export const zBodySetRecipePhotoV1RecipesRecipeIdPhotoPut = z.object({
    file: z.string()
});

export const zBodyUploadAttachmentV1GuidesGuideIdAttachmentsPost = z.object({
    file: z.string()
});

export const zCaptureCreate = z.object({
    raw_text: z.string().min(1).max(500)
});

export const zCaptureResponse = z.object({
    id: z.string().uuid(),
    raw_text: z.string(),
    status: z.enum([
        'proposed',
        'confirmed',
        'dismissed',
        'auto'
    ]),
    tags: z.array(z.string()),
    proposal: z.object({
        target: z.enum([
            'shopping',
            'task',
            'note',
            'none'
        ]),
        label: z.string(),
        qty: z.union([
            z.string(),
            z.null()
        ]).optional(),
        unit: z.union([
            z.string(),
            z.null()
        ]).optional(),
        assignee_hint: z.union([
            z.string(),
            z.null()
        ]).optional(),
        tags: z.array(z.string()).optional(),
        when: z.union([
            z.string(),
            z.null()
        ]).optional(),
        follow_up: z.union([
            z.object({
                label: z.string()
            }),
            z.null()
        ]).optional()
    }),
    created_at: z.string().datetime()
});

export const zChallengeResponse = z.object({
    standings: z.array(z.object({
        member_id: z.string().uuid(),
        points: z.number().int()
    })),
    thanks_remaining: z.number().int()
});

export const zChallengeStanding = z.object({
    member_id: z.string().uuid(),
    points: z.number().int()
});

export const zChangeRoleRequest = z.object({
    role: z.enum([
        'admin',
        'member',
        'child',
        'guest'
    ])
});

export const zChildLoginRequest = z.object({
    household_id: z.string().uuid(),
    username: z.string().min(1).max(50),
    pin: z.string().min(1).max(8)
});

export const zChildResponse = z.object({
    user_id: z.string().uuid(),
    username: z.string(),
    display_name: z.string()
});

export const zCommentCreate = z.object({
    object_type: z.string().min(1).max(40),
    object_id: z.string().uuid(),
    body_md: z.string().min(1).max(10000)
});

export const zCommentResponse = z.object({
    id: z.string().uuid(),
    object_type: z.string(),
    object_id: z.string().uuid(),
    author_id: z.string().uuid(),
    body_md: z.string(),
    version: z.number().int(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zCommentUpdate = z.object({
    body_md: z.string().min(1).max(10000)
});

export const zConnectionResponse = z.object({
    id: z.string().uuid(),
    member_id: z.string().uuid(),
    provider: z.string(),
    status: z.string(),
    has_tokens: z.boolean(),
    consent_types: z.array(z.string()),
    scopes: z.array(z.string()),
    last_sync_at: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    last_error: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zConsentUpdate = z.object({
    consent_types: z.array(z.string())
});

export const zCookTaskResult = z.object({
    title: z.string(),
    assigned_to: z.string().uuid()
});

export const zCorrectionRequest = z.object({
    member_id: z.string().uuid(),
    amount: z.number().int().gte(-100000).lte(100000),
    note: z.union([
        z.string().max(500),
        z.null()
    ]).optional()
});

export const zCreateChildRequest = z.object({
    display_name: z.string().min(1).max(100),
    username: z.string().min(1).max(50),
    pin: z.string().min(4).max(8)
});

export const zCreateHouseholdRequest = z.object({
    name: z.string().min(1).max(120)
});

export const zCreateInviteRequest = z.object({
    role: z.enum([
        'admin',
        'member',
        'child',
        'guest'
    ]).optional(),
    max_uses: z.number().int().gte(1).lte(100).optional().default(1),
    expires_in_hours: z.number().int().gte(1).lte(8760).optional().default(168)
});

export const zCurrentWeather = z.object({
    temperature_c: z.number(),
    weather_code: z.number().int(),
    is_day: z.boolean()
});

export const zDailyMetric = z.object({
    day: z.string().date(),
    new_households: z.number().int(),
    new_users: z.number().int()
});

export const zDailyWeather = z.object({
    date: z.string(),
    temp_min_c: z.number(),
    temp_max_c: z.number(),
    weather_code: z.number().int(),
    precipitation_probability_max: z.union([
        z.number().int(),
        z.null()
    ])
});

export const zDeletionBlockerResponse = z.object({
    household_id: z.string().uuid(),
    name: z.string(),
    reason: z.string()
});

export const zDiagnosticEntry = z.object({
    at: z.string().max(40),
    route: z.union([
        z.string().max(120),
        z.null()
    ]).optional(),
    error_ref: z.union([
        z.string().max(64),
        z.null()
    ]).optional(),
    status: z.union([
        z.number().int().gte(0).lte(599),
        z.null()
    ]).optional()
});

export const zDigestSetting = z.object({
    enabled: z.boolean()
});

export const zDissolveHouseholdRequest = z.object({
    confirm_name: z.string().min(1).max(200)
});

export const zDissolvePreview = z.object({
    household_name: z.string(),
    member_count: z.number().int(),
    child_account_count: z.number().int()
});

export const zEmailVerifyRequest = z.object({
    token: z.string().min(1).max(256)
});

export const zEnvelopeResponse = z.object({
    id: z.string().uuid(),
    member_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    kind: z.string(),
    key_version: z.number().int(),
    wrapped_key: z.string(),
    wrap_meta: z.object({}),
    created_at: z.string().datetime()
});

export const zEnvelopeUpsert = z.object({
    kind: z.enum([
        'passphrase',
        'recovery'
    ]),
    key_version: z.number().int().gte(1).optional().default(1),
    wrapped_key: z.string().min(1).max(8000),
    wrap_meta: z.object({}).optional()
});

export const zEventCreate = z.object({
    title: z.string().min(1).max(200),
    description: z.union([
        z.string().max(4000),
        z.null()
    ]).optional(),
    location: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    starts_at: z.string().datetime(),
    ends_at: z.string().datetime(),
    all_day: z.boolean().optional().default(false),
    layer: z.enum([
        'household',
        'personal'
    ]).optional(),
    busy: z.boolean().optional().default(true),
    kind: z.enum([
        'normal',
        'absence',
        'guest'
    ]).optional(),
    rrule: z.union([
        z.string().max(500),
        z.null()
    ]).optional(),
    tzid: z.string().max(64).optional().default('UTC'),
    subscription_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zEventResponse = z.object({
    id: z.string().uuid(),
    series_id: z.string().uuid(),
    owner_id: z.string().uuid(),
    title: z.string(),
    description: z.union([
        z.string(),
        z.null()
    ]),
    location: z.union([
        z.string(),
        z.null()
    ]),
    starts_at: z.string().datetime(),
    ends_at: z.string().datetime(),
    original_start: z.union([
        z.string().datetime(),
        z.null()
    ]),
    all_day: z.boolean(),
    layer: z.enum([
        'household',
        'personal'
    ]),
    busy: z.boolean(),
    kind: z.enum([
        'normal',
        'absence',
        'guest'
    ]),
    rrule: z.union([
        z.string(),
        z.null()
    ]),
    recurring: z.boolean(),
    exdates: z.array(z.string().datetime()),
    tzid: z.string(),
    external: z.boolean().optional().default(false)
});

export const zEventUpdate = z.object({
    title: z.union([
        z.string().min(1).max(200),
        z.null()
    ]).optional(),
    description: z.union([
        z.string().max(4000),
        z.null()
    ]).optional(),
    location: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    starts_at: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    ends_at: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    all_day: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    layer: z.union([
        z.enum([
            'household',
            'personal'
        ]),
        z.null()
    ]).optional(),
    busy: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    kind: z.union([
        z.enum([
            'normal',
            'absence',
            'guest'
        ]),
        z.null()
    ]).optional(),
    rrule: z.union([
        z.string().max(500),
        z.null()
    ]).optional(),
    tzid: z.union([
        z.string().max(64),
        z.null()
    ]).optional()
});

export const zFairnessEntry = z.object({
    member_id: z.string().uuid(),
    load: z.number().int()
});

export const zFairnessResponse = z.object({
    window_days: z.number().int(),
    entries: z.array(zFairnessEntry)
});

export const zFeedResponse = z.object({
    url: z.string()
});

export const zFeedbackCreate = z.object({
    category: z.enum([
        'bug',
        'idea',
        'praise',
        'other'
    ]),
    message: z.string().min(1).max(5000),
    error_ref: z.union([
        z.string().max(64),
        z.null()
    ]).optional(),
    route: z.union([
        z.string().max(120),
        z.null()
    ]).optional(),
    diagnostics: z.union([
        z.object({
            app_version: z.string().max(40),
            entries: z.array(zDiagnosticEntry).max(25).optional()
        }),
        z.null()
    ]).optional()
});

export const zFeedbackDiagnostics = z.object({
    app_version: z.string().max(40),
    entries: z.array(zDiagnosticEntry).max(25).optional()
});

export const zFeedbackResponse = z.object({
    id: z.string().uuid(),
    category: z.enum([
        'bug',
        'idea',
        'praise',
        'other'
    ]),
    message: z.string(),
    error_ref: z.union([
        z.string(),
        z.null()
    ]),
    route: z.union([
        z.string(),
        z.null()
    ]),
    created_at: z.string().datetime()
});

export const zFlagSet = z.object({
    enabled: z.boolean()
});

export const zFollowUp = z.object({
    label: z.string()
});

export const zForecast = z.object({
    current: z.union([
        zCurrentWeather,
        z.null()
    ]),
    daily: z.array(zDailyWeather)
});

export const zGenerateResult = z.object({
    added: z.number().int()
});

export const zGeocodeResult = z.object({
    name: z.string(),
    lat: z.number(),
    lon: z.number(),
    country: z.union([
        z.string(),
        z.null()
    ]),
    admin1: z.union([
        z.string(),
        z.null()
    ])
});

export const zGuideCreate = z.object({
    title: z.string().min(1).max(200),
    body_md: z.string().max(200000).optional().default(''),
    category: z.string().max(80).optional().default(''),
    tags: z.array(z.string()).optional(),
    contact_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zGuideResponse = z.object({
    id: z.string().uuid(),
    title: z.string(),
    body_md: z.string(),
    category: z.string(),
    tags: z.array(z.string()),
    contact_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    author_id: z.string().uuid(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zGuideSummary = z.object({
    id: z.string().uuid(),
    title: z.string(),
    category: z.string(),
    tags: z.array(z.string()),
    contact_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    updated_at: z.string().datetime()
});

export const zGuideUpdate = z.object({
    title: z.union([
        z.string().min(1).max(200),
        z.null()
    ]).optional(),
    body_md: z.union([
        z.string().max(200000),
        z.null()
    ]).optional(),
    category: z.union([
        z.string().max(80),
        z.null()
    ]).optional(),
    tags: z.union([
        z.array(z.string()),
        z.null()
    ]).optional(),
    contact_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zHttpValidationError = z.object({
    detail: z.array(z.object({
        loc: z.array(z.unknown()),
        msg: z.string(),
        type: z.string(),
        input: z.unknown().optional(),
        ctx: z.object({}).optional()
    })).optional()
});

export const zHouseholdMetadata = z.object({
    id: z.string().uuid(),
    name: z.string(),
    created_at: z.string().datetime(),
    member_count: z.number().int(),
    admin_count: z.number().int()
});

export const zHouseholdSummary = z.object({
    household_id: z.string().uuid(),
    name: z.string(),
    role: z.enum([
        'admin',
        'member',
        'child',
        'guest'
    ])
});

export const zIcsImportRequest = z.object({
    content: z.string().min(1).max(1000000),
    layer: z.enum([
        'household',
        'personal'
    ]).optional()
});

export const zIcsImportResult = z.object({
    imported: z.number().int(),
    skipped: z.number().int(),
    failed: z.number().int()
});

export const zIngredientLine = z.object({
    raw_text: z.string().min(1).max(500),
    qty: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    unit: z.union([
        z.string().max(40),
        z.null()
    ]).optional()
});

export const zIngredientOut = z.object({
    id: z.string().uuid(),
    name_de: z.string(),
    name_en: z.string(),
    category: z.string(),
    default_unit: z.string()
});

export const zIngredientResponse = z.object({
    raw_text: z.string(),
    qty: z.union([
        z.string(),
        z.null()
    ]),
    unit: z.union([
        z.string(),
        z.null()
    ]),
    ingredient_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    ingredient_name: z.union([
        z.string(),
        z.null()
    ])
});

export const zInviteResponse = z.object({
    code: z.string()
});

export const zJoinRequest = z.object({
    code: z.string().min(1).max(48)
});

export const zLedgerEntryResponse = z.object({
    id: z.string().uuid(),
    from_account: z.string(),
    to_account: z.string(),
    amount: z.number().int(),
    ref_type: z.string(),
    ref_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    note: z.union([
        z.string(),
        z.null()
    ]),
    created_at: z.string().datetime()
});

export const zLetterCreate = z.object({
    subject: z.string().min(1).max(200),
    body_md: z.string().max(50000).optional().default(''),
    to_ids: z.array(z.string().uuid()).optional()
});

export const zLetterResponse = z.object({
    id: z.string().uuid(),
    subject: z.string(),
    body_md: z.string(),
    from_id: z.string().uuid(),
    to_ids: z.array(z.string().uuid()),
    created_at: z.string().datetime(),
    read_by_me: z.boolean(),
    read_count: z.number().int()
});

export const zLetterSummary = z.object({
    id: z.string().uuid(),
    subject: z.string(),
    from_id: z.string().uuid(),
    to_ids: z.array(z.string().uuid()),
    created_at: z.string().datetime(),
    read_by_me: z.boolean(),
    read_count: z.number().int()
});

export const zLetterToTaskResult = z.object({
    task_id: z.string().uuid(),
    title: z.string()
});

export const zLinkCreate = z.object({
    a_type: z.string().min(1).max(40),
    a_id: z.string().uuid(),
    b_type: z.string().min(1).max(40),
    b_id: z.string().uuid(),
    relation: z.string().min(1).max(40).optional().default('related')
});

export const zLinkResponse = z.object({
    id: z.string().uuid(),
    src_type: z.string(),
    src_id: z.string().uuid(),
    dst_type: z.string(),
    dst_id: z.string().uuid(),
    relation: z.string(),
    created_at: z.string().datetime()
});

export const zListingCreate = z.object({
    task_instance_id: z.string().uuid(),
    price: z.number().int().gte(1).lte(100000)
});

export const zListingResponse = z.object({
    id: z.string().uuid(),
    task_instance_id: z.string().uuid(),
    title: z.string(),
    seller_id: z.string().uuid(),
    price: z.number().int(),
    status: z.enum([
        'open',
        'accepted',
        'settled',
        'reverted',
        'withdrawn'
    ]),
    buyer_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    created_at: z.string().datetime()
});

export const zLocationIn = z.object({
    lat: z.number().gte(-90).lte(90),
    lon: z.number().gte(-180).lte(180),
    label: z.union([
        z.string().max(120),
        z.null()
    ]).optional()
});

export const zLocationResponse = z.object({
    lat: z.number(),
    lon: z.number(),
    label: z.union([
        z.string(),
        z.null()
    ])
});

export const zLoginEventResponse = z.object({
    success: z.boolean(),
    country_code: z.union([
        z.string(),
        z.null()
    ]),
    created_at: z.string().datetime()
});

export const zLoginRequest = z.object({
    email: z.string().min(3).max(320),
    password: z.string().min(1).max(1024),
    totp_code: z.union([
        z.string().max(8),
        z.null()
    ]).optional(),
    recovery_code: z.union([
        z.string().max(64),
        z.null()
    ]).optional()
});

export const zMeResponse = z.object({
    user_id: z.string().uuid(),
    email: z.union([
        z.string(),
        z.null()
    ]),
    display_name: z.string(),
    household_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    role: z.union([
        z.enum([
            'admin',
            'member',
            'child',
            'guest'
        ]),
        z.null()
    ]),
    totp_enabled: z.boolean(),
    recovery_codes_remaining: z.number().int(),
    email_verified: z.boolean(),
    flags: z.object({})
});

export const zMealSlotResponse = z.object({
    day_of_week: z.number().int(),
    slot: z.enum([
        'breakfast',
        'lunch',
        'dinner',
        'snack'
    ]),
    recipe_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    recipe_title: z.union([
        z.string(),
        z.null()
    ]),
    free_text: z.union([
        z.string(),
        z.null()
    ]),
    cook_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    note: z.union([
        z.string(),
        z.null()
    ])
});

export const zMemberResponse = z.object({
    membership_id: z.string().uuid(),
    user_id: z.string().uuid(),
    role: z.enum([
        'admin',
        'member',
        'child',
        'guest'
    ]),
    display_name: z.string()
});

export const zNoteCreate = z.object({
    title: z.string().min(1).max(200),
    body_md: z.string().max(50000).optional().default(''),
    pinned: z.boolean().optional().default(false)
});

export const zNoteResponse = z.object({
    id: z.string().uuid(),
    title: z.string(),
    body_md: z.string(),
    pinned: z.boolean(),
    author_id: z.string().uuid(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zNoteSummary = z.object({
    id: z.string().uuid(),
    title: z.string(),
    pinned: z.boolean(),
    author_id: z.string().uuid(),
    updated_at: z.string().datetime()
});

export const zNoteUpdate = z.object({
    title: z.union([
        z.string().min(1).max(200),
        z.null()
    ]).optional(),
    body_md: z.union([
        z.string().max(50000),
        z.null()
    ]).optional(),
    pinned: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

export const zNoteVersionResponse = z.object({
    version_no: z.number().int(),
    title: z.string(),
    body_md: z.string(),
    edited_by: z.string().uuid(),
    created_at: z.string().datetime()
});

export const zNutritionOut = z.object({
    kcal: z.number(),
    protein_g: z.number(),
    fat_g: z.number(),
    carbs_g: z.number(),
    sugar_g: z.number(),
    fiber_g: z.number(),
    confidence: z.string(),
    covered: z.number().int(),
    total: z.number().int()
});

export const zOccurrenceMove = z.object({
    occurrence_start: z.string().datetime(),
    new_start: z.string().datetime(),
    new_end: z.string().datetime()
});

export const zOccurrenceRef = z.object({
    occurrence_start: z.string().datetime()
});

export const zOperatorLogin = z.object({
    email: z.string().min(3).max(320),
    password: z.string().min(1).max(512),
    totp_code: z.string().min(6).max(10)
});

export const zOperatorMe = z.object({
    id: z.string().uuid(),
    email: z.string()
});

export const zOperatorPasskeySummary = z.object({
    id: z.string().uuid(),
    name: z.string(),
    created_at: z.string().datetime(),
    last_used_at: z.union([
        z.string().datetime(),
        z.null()
    ])
});

export const zOperatorSession = z.object({
    token: z.string()
});

export const zOperatorSummary = z.object({
    id: z.string().uuid(),
    email: z.string(),
    totp_enabled: z.boolean(),
    is_active: z.boolean(),
    created_at: z.string().datetime()
});

export const zOpsFeedbackEntry = z.object({
    id: z.string().uuid(),
    household_id: z.string().uuid(),
    category: z.string(),
    message: z.string(),
    error_ref: z.union([
        z.string(),
        z.null()
    ]),
    route: z.union([
        z.string(),
        z.null()
    ]),
    diagnostics: z.union([
        z.object({}),
        z.null()
    ]).optional(),
    created_at: z.string().datetime()
});

export const zOpsFlags = z.object({
    overrides: z.object({}),
    available: z.array(z.string())
});

export const zOpsHealth = z.object({
    env: z.string(),
    app_version: z.string(),
    git_sha: z.string()
});

export const zOpsKpis = z.object({
    usage: z.object({
        households: z.number().int(),
        users: z.number().int(),
        adult_members: z.number().int(),
        children: z.number().int()
    }),
    daily: z.array(zDailyMetric)
});

export const zOpsPasskeyLoginComplete = z.object({
    credential: z.object({}),
    flow_id: z.string()
});

export const zOpsPasskeyLoginOptions = z.object({
    options: z.object({}),
    flow_id: z.string()
});

export const zOpsPasskeyOptions = z.object({
    options: z.object({})
});

export const zOpsPasskeyRegisterComplete = z.object({
    credential: z.object({}),
    name: z.string().max(120).optional().default('')
});

export const zParsedProposal = z.object({
    target: z.enum([
        'shopping',
        'task',
        'note',
        'none'
    ]),
    label: z.string(),
    qty: z.union([
        z.string(),
        z.null()
    ]).optional(),
    unit: z.union([
        z.string(),
        z.null()
    ]).optional(),
    assignee_hint: z.union([
        z.string(),
        z.null()
    ]).optional(),
    tags: z.array(z.string()).optional(),
    when: z.union([
        z.string(),
        z.null()
    ]).optional(),
    follow_up: z.union([
        zFollowUp,
        z.null()
    ]).optional()
});

export const zPasskeyLoginComplete = z.object({
    credential: z.object({})
});

export const zPasskeyOptions = z.object({
    options: z.object({})
});

export const zPasskeyRegisterComplete = z.object({
    credential: z.object({}),
    name: z.string().max(120).optional().default('')
});

export const zPasskeyResponse = z.object({
    id: z.string().uuid(),
    name: z.string(),
    created_at: z.string().datetime(),
    last_used_at: z.union([
        z.string().datetime(),
        z.null()
    ])
});

export const zPasswordForgotRequest = z.object({
    email: z.string().min(3).max(320)
});

export const zPasswordResetRequest = z.object({
    token: z.string().min(1).max(256),
    password: z.string().min(1).max(1024)
});

export const zPersonalSuggestionResponse = z.object({
    recipe_id: z.string().uuid(),
    title: z.string(),
    total_minutes: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    reasons: z.array(z.string()).optional().default([])
});

export const zPrepTaskResult = z.object({
    title: z.string(),
    assigned_to: z.string().uuid(),
    hint: z.string()
});

export const zProfileResponse = z.object({
    display_name: z.string(),
    locale: z.string(),
    work_hours: z.string(),
    dietary: z.array(z.string()),
    notifications: z.object({}),
    version: z.number().int()
});

export const zProfileUpdate = z.object({
    display_name: z.union([
        z.string().min(1).max(100),
        z.null()
    ]).optional(),
    locale: z.union([
        z.string().max(10),
        z.null()
    ]).optional(),
    work_hours: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    dietary: z.union([
        z.array(z.string()),
        z.null()
    ]).optional(),
    notifications: z.union([
        z.object({}),
        z.null()
    ]).optional()
});

export const zRecipeCreate = z.object({
    title: z.string().min(1).max(200),
    servings: z.number().int().gte(1).lte(100).optional().default(1),
    steps_md: z.string().max(20000).optional().default(''),
    prep_minutes: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    cook_minutes: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    tags: z.array(z.string()).optional(),
    source_url: z.union([
        z.string().max(2000),
        z.null()
    ]).optional(),
    ingredients: z.array(zIngredientLine).optional()
});

export const zRecipeImportRequest = z.object({
    url: z.string().min(1).max(2000)
});

export const zRecipeImportResponse = z.object({
    title: z.string(),
    servings: z.number().int(),
    steps_md: z.string(),
    tags: z.array(z.string()),
    source_url: z.string(),
    ingredients: z.array(zIngredientLine)
});

export const zRecipeResponse = z.object({
    id: z.string().uuid(),
    title: z.string(),
    servings: z.number().int(),
    steps_md: z.string(),
    prep_minutes: z.union([
        z.number().int(),
        z.null()
    ]),
    cook_minutes: z.union([
        z.number().int(),
        z.null()
    ]),
    tags: z.array(z.string()),
    source_url: z.union([
        z.string(),
        z.null()
    ]),
    ingredients: z.array(zIngredientResponse),
    version: z.number().int(),
    has_photo: z.boolean(),
    last_cooked_at: z.union([
        z.string().datetime(),
        z.null()
    ])
});

export const zRecipeSummary = z.object({
    id: z.string().uuid(),
    title: z.string(),
    servings: z.number().int(),
    tags: z.array(z.string()),
    has_photo: z.boolean(),
    last_cooked_at: z.union([
        z.string().datetime(),
        z.null()
    ])
});

export const zRecipeUpdate = z.object({
    title: z.union([
        z.string().min(1).max(200),
        z.null()
    ]).optional(),
    servings: z.union([
        z.number().int().gte(1).lte(100),
        z.null()
    ]).optional(),
    steps_md: z.union([
        z.string().max(20000),
        z.null()
    ]).optional(),
    prep_minutes: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    cook_minutes: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    tags: z.union([
        z.array(z.string()),
        z.null()
    ]).optional(),
    source_url: z.union([
        z.string().max(2000),
        z.null()
    ]).optional(),
    ingredients: z.union([
        z.array(zIngredientLine),
        z.null()
    ]).optional()
});

export const zRecoveryCodesResponse = z.object({
    recovery_codes: z.array(z.string())
});

export const zRedemptionResponse = z.object({
    id: z.string().uuid(),
    reward_id: z.string().uuid(),
    member_id: z.string().uuid(),
    title: z.string(),
    cost: z.number().int(),
    status: z.enum([
        'requested',
        'fulfilled'
    ]),
    created_at: z.string().datetime()
});

export const zRegisterRequest = z.object({
    email: z.string().min(3).max(320),
    password: z.string().min(1).max(1024),
    display_name: z.string().min(1).max(100),
    locale: z.string().max(10).optional().default('de')
});

export const zRewardCreate = z.object({
    title: z.string().min(1).max(200),
    description: z.union([
        z.string().max(2000),
        z.null()
    ]).optional(),
    cost: z.number().int().lte(100000),
    stock: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    cooldown_hours: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    kind: z.enum([
        'standard',
        'mealplan_wish',
        'custom'
    ]).optional(),
    active: z.boolean().optional().default(true)
});

export const zRewardResponse = z.object({
    id: z.string().uuid(),
    title: z.string(),
    description: z.union([
        z.string(),
        z.null()
    ]),
    cost: z.number().int(),
    stock: z.union([
        z.number().int(),
        z.null()
    ]),
    cooldown_hours: z.union([
        z.number().int(),
        z.null()
    ]),
    kind: z.enum([
        'standard',
        'mealplan_wish',
        'custom'
    ]),
    active: z.boolean(),
    version: z.number().int()
});

export const zRewardUpdate = z.object({
    title: z.union([
        z.string().min(1).max(200),
        z.null()
    ]).optional(),
    description: z.union([
        z.string().max(2000),
        z.null()
    ]).optional(),
    cost: z.union([
        z.number().int().lte(100000),
        z.null()
    ]).optional(),
    stock: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    cooldown_hours: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    kind: z.union([
        z.enum([
            'standard',
            'mealplan_wish',
            'custom'
        ]),
        z.null()
    ]).optional(),
    active: z.union([
        z.boolean(),
        z.null()
    ]).optional()
});

export const zRole = z.enum([
    'admin',
    'member',
    'child',
    'guest'
]);

export const zRoomCreate = z.object({
    name: z.string().min(1).max(100),
    icon: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    decay_days: z.number().int().lte(3650)
});

export const zRoomHeatmapEntry = z.object({
    room_id: z.string().uuid(),
    name: z.string(),
    icon: z.union([
        z.string(),
        z.null()
    ]),
    decay_days: z.number().int(),
    last_done: z.union([
        z.string().datetime(),
        z.null()
    ]),
    status: z.enum([
        'green',
        'amber',
        'red'
    ])
});

export const zRoomResponse = z.object({
    id: z.string().uuid(),
    name: z.string(),
    icon: z.union([
        z.string(),
        z.null()
    ]),
    decay_days: z.number().int(),
    version: z.number().int()
});

export const zRoomUpdate = z.object({
    name: z.union([
        z.string().min(1).max(100),
        z.null()
    ]).optional(),
    icon: z.union([
        z.string().max(40),
        z.null()
    ]).optional(),
    decay_days: z.union([
        z.number().int().lte(3650),
        z.null()
    ]).optional()
});

export const zServerEntityState = z.object({
    entity: z.string(),
    id: z.string().uuid(),
    version: z.number().int(),
    deleted: z.boolean(),
    fields: z.object({})
});

export const zSessionResponse = z.object({
    user_id: z.string().uuid(),
    household_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    role: z.union([
        zRole,
        z.null()
    ]).optional()
});

export const zSessionView = z.object({
    family_id: z.string().uuid(),
    device_label: z.string(),
    user_agent: z.union([
        z.string(),
        z.null()
    ]),
    last_used_at: z.string().datetime(),
    current: z.boolean()
});

export const zSlotResponse = z.object({
    start: z.string().datetime(),
    end: z.string().datetime(),
    reasons: z.array(z.string())
});

export const zSlotSet = z.object({
    day_of_week: z.number().int().gte(0).lte(6),
    slot: z.enum([
        'breakfast',
        'lunch',
        'dinner',
        'snack'
    ]),
    recipe_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    free_text: z.union([
        z.string().max(200),
        z.null()
    ]).optional(),
    cook_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    note: z.union([
        z.string().max(200),
        z.null()
    ]).optional()
});

export const zSubscriptionCheckResponse = z.object({
    ok: z.boolean(),
    category: z.union([
        z.string(),
        z.null()
    ]).optional(),
    objects: z.union([
        z.number().int(),
        z.null()
    ]).optional()
});

export const zSubscriptionCreate = z.object({
    label: z.string().min(1).max(100),
    caldav_url: z.string().min(1).max(2000),
    username: z.union([
        z.string().min(1).max(255),
        z.null()
    ]).optional(),
    password: z.union([
        z.string().min(1).max(1024),
        z.null()
    ]).optional(),
    enabled: z.boolean().optional().default(true)
});

export const zSubscriptionResponse = z.object({
    id: z.string().uuid(),
    member_id: z.string().uuid(),
    label: z.string(),
    caldav_url: z.string(),
    enabled: z.boolean(),
    has_credentials: z.boolean(),
    last_sync_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    last_sync_error: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zSubscriptionUpdate = z.object({
    label: z.union([
        z.string().min(1).max(100),
        z.null()
    ]).optional(),
    caldav_url: z.union([
        z.string().min(1).max(2000),
        z.null()
    ]).optional(),
    username: z.union([
        z.string().min(1).max(255),
        z.null()
    ]).optional(),
    password: z.union([
        z.string().min(1).max(1024),
        z.null()
    ]).optional(),
    enabled: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    clear_credentials: z.boolean().optional().default(false)
});

export const zSyncBatchRequest = z.object({
    ops: z.array(z.object({
        client_op_id: z.string().uuid(),
        entity: z.string(),
        id: z.string().uuid(),
        base_version: z.number().int().optional().default(0),
        op: z.enum([
            'upsert',
            'delete'
        ]),
        fields: z.object({}).optional()
    })).max(500)
});

export const zSyncBatchResponse = z.object({
    applied: z.array(zServerEntityState)
});

export const zSyncChange = z.object({
    entity: z.string(),
    id: z.string().uuid(),
    op: z.enum([
        'upsert',
        'delete'
    ]),
    version: z.number().int(),
    updated_at: z.string().datetime(),
    fields: z.object({})
});

export const zSyncOp = z.object({
    client_op_id: z.string().uuid(),
    entity: z.string(),
    id: z.string().uuid(),
    base_version: z.number().int().optional().default(0),
    op: z.enum([
        'upsert',
        'delete'
    ]),
    fields: z.object({}).optional()
});

export const zSyncPullResponse = z.object({
    changes: z.array(zSyncChange),
    next_cursor: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zTaskInstanceCreate = z.object({
    template_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    title: z.union([
        z.string().min(1).max(200),
        z.null()
    ]).optional(),
    assigned_to: z.union([
        z.string().uuid(),
        z.null()
    ]).optional(),
    due_at: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    room_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zTaskInstanceResponse = z.object({
    id: z.string().uuid(),
    template_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    title: z.string(),
    points: z.number().int(),
    assigned_to: z.union([
        z.string().uuid(),
        z.null()
    ]),
    due_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    status: z.enum([
        'open',
        'done',
        'expired',
        'armed'
    ]),
    done_at: z.union([
        z.string().datetime(),
        z.null()
    ]),
    done_by: z.union([
        z.string().uuid(),
        z.null()
    ]),
    awarded_points: z.union([
        z.number().int(),
        z.null()
    ]),
    room_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    version: z.number().int()
});

export const zTaskTemplateCreate = z.object({
    title: z.string().min(1).max(200),
    description: z.union([
        z.string().max(2000),
        z.null()
    ]).optional(),
    points: z.number().int().gte(0).lte(100000).optional().default(0),
    duration_est_minutes: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    outdoor: z.boolean().optional().default(false),
    rotation: z.enum([
        'fair',
        'fixed',
        'open'
    ]).optional(),
    room_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zTaskTemplateResponse = z.object({
    id: z.string().uuid(),
    title: z.string(),
    description: z.union([
        z.string(),
        z.null()
    ]),
    points: z.number().int(),
    duration_est_minutes: z.union([
        z.number().int(),
        z.null()
    ]),
    outdoor: z.boolean(),
    rotation: z.enum([
        'fair',
        'fixed',
        'open'
    ]),
    room_id: z.union([
        z.string().uuid(),
        z.null()
    ]),
    version: z.number().int()
});

export const zTaskTemplateSummary = z.object({
    id: z.string().uuid(),
    title: z.string(),
    points: z.number().int(),
    outdoor: z.boolean(),
    rotation: z.enum([
        'fair',
        'fixed',
        'open'
    ]),
    room_id: z.union([
        z.string().uuid(),
        z.null()
    ])
});

export const zTaskTemplateUpdate = z.object({
    title: z.union([
        z.string().min(1).max(200),
        z.null()
    ]).optional(),
    description: z.union([
        z.string().max(2000),
        z.null()
    ]).optional(),
    points: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    duration_est_minutes: z.union([
        z.number().int().gte(0).lte(100000),
        z.null()
    ]).optional(),
    outdoor: z.union([
        z.boolean(),
        z.null()
    ]).optional(),
    rotation: z.union([
        z.enum([
            'fair',
            'fixed',
            'open'
        ]),
        z.null()
    ]).optional(),
    room_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zThanksRequest = z.object({
    to_member_id: z.string().uuid(),
    amount: z.number().int().gte(1).lte(100),
    note: z.union([
        z.string().max(200),
        z.null()
    ]).optional()
});

export const zThanksResponse = z.object({
    remaining_this_week: z.number().int()
});

export const zToTaskResult = z.object({
    task_id: z.string().uuid(),
    title: z.string()
});

export const zTotpCodeRequest = z.object({
    code: z.string().min(6).max(8)
});

export const zTotpSetupResponse = z.object({
    secret: z.string(),
    otpauth_uri: z.string()
});

export const zTrashedNote = z.object({
    id: z.string().uuid(),
    title: z.string(),
    deleted_at: z.string().datetime()
});

export const zUnreadCount = z.object({
    unread: z.number().int()
});

export const zUsageCounters = z.object({
    households: z.number().int(),
    users: z.number().int(),
    adult_members: z.number().int(),
    children: z.number().int()
});

export const zValidationError = z.object({
    loc: z.array(z.unknown()),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.object({}).optional()
});

export const zVaultItemCreate = z.object({
    key_version: z.number().int().gte(1).optional().default(1),
    ciphertext: z.string().min(1).max(500000),
    item_meta: z.object({}).optional()
});

export const zVaultItemResponse = z.object({
    id: z.string().uuid(),
    author_id: z.string().uuid(),
    key_version: z.number().int(),
    ciphertext: z.string(),
    item_meta: z.object({}),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zVaultItemSummary = z.object({
    id: z.string().uuid(),
    key_version: z.number().int(),
    item_meta: z.object({}),
    updated_at: z.string().datetime()
});

export const zVaultItemUpdate = z.object({
    key_version: z.union([
        z.number().int().gte(1),
        z.null()
    ]).optional(),
    ciphertext: z.union([
        z.string().min(1).max(500000),
        z.null()
    ]).optional(),
    item_meta: z.union([
        z.object({}),
        z.null()
    ]).optional()
});

export const zWeatherResponse = z.object({
    configured: z.boolean(),
    location: z.union([
        zLocationResponse,
        z.null()
    ]),
    forecast: z.union([
        zForecast,
        z.null()
    ])
});

export const zWeekNutrition = z.object({
    kcal: z.number(),
    protein_g: z.number(),
    fat_g: z.number(),
    carbs_g: z.number(),
    meals_counted: z.number().int(),
    confidence: z.string(),
    target_kcal: z.union([
        z.number(),
        z.null()
    ]).optional(),
    verdict: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zWeekResponse = z.object({
    week_start: z.string().date(),
    slots: z.array(zMealSlotResponse),
    absent_days: z.array(z.number().int()).optional()
});

export const zExportMeV1MeExportGetResponse = z.string();

export const zExportHouseholdV1HouseholdExportGetResponse = z.string();

export const zRegisterV1AuthRegisterPostResponse = zSessionResponse;

export const zLoginV1AuthLoginPostResponse = zSessionResponse;

export const zChildLoginV1AuthChildLoginPostResponse = zSessionResponse;

export const zRefreshV1AuthRefreshPostResponse = zSessionResponse;

export const zLogoutV1AuthLogoutPostResponse = z.void();

export const zMeV1AuthMeGetResponse = zMeResponse;

export const zPasswordForgotV1AuthPasswordForgotPostResponse = z.void();

export const zPasswordResetV1AuthPasswordResetPostResponse = z.void();

export const zEmailVerifyRequestV1AuthEmailVerifyRequestPostResponse = z.void();

export const zEmailVerifyConfirmV1AuthEmailVerifyConfirmPostResponse = z.void();

export const zTotpSetupV1AuthTotpSetupPostResponse = zTotpSetupResponse;

export const zTotpEnableV1AuthTotpEnablePostResponse = zRecoveryCodesResponse;

export const zTotpDisableV1AuthTotpDisablePostResponse = z.void();

export const zRegenerateRecoveryCodesV1AuthTotpRecoveryCodesPostResponse = zRecoveryCodesResponse;

export const zPasskeysRegisterBeginV1AuthPasskeysRegisterBeginPostResponse = zPasskeyOptions;

export const zPasskeysRegisterCompleteV1AuthPasskeysRegisterCompletePostResponse = z.void();

export const zPasskeysLoginBeginV1AuthPasskeysLoginBeginPostResponse = zPasskeyOptions;

export const zPasskeysLoginCompleteV1AuthPasskeysLoginCompletePostResponse = zSessionResponse;

export const zPasskeysListV1AuthPasskeysGetResponse = z.array(zPasskeyResponse);

export const zPasskeysDeleteV1AuthPasskeysPasskeyIdDeleteResponse = z.void();

export const zDeleteOwnAccountV1AuthAccountDeleteResponse = z.void();

export const zAccountDeletionBlockersV1AuthAccountDeletionBlockersGetResponse = z.array(zDeletionBlockerResponse);

export const zListSessionsV1AuthSessionsGetResponse = z.array(zSessionView);

export const zRevokeSessionV1AuthSessionsFamilyIdDeleteResponse = z.void();

export const zListLoginEventsV1AuthLoginEventsGetResponse = z.array(zLoginEventResponse);

export const zGetAccountProfileV1AccountProfileGetResponse = zProfileResponse;

export const zPatchAccountProfileV1AccountProfilePatchResponse = zProfileResponse;

export const zListHouseholdsV1HouseholdsGetResponse = z.array(zHouseholdSummary);

export const zCreateHouseholdV1HouseholdsPostResponse = zSessionResponse;

export const zSwitchHouseholdV1HouseholdsHouseholdIdSwitchPostResponse = zSessionResponse;

export const zJoinHouseholdV1HouseholdsJoinPostResponse = zSessionResponse;

export const zCreateHouseholdInviteV1HouseholdInvitesPostResponse = zInviteResponse;

export const zGetHouseholdDigestV1HouseholdDigestGetResponse = zDigestSetting;

export const zPatchHouseholdDigestV1HouseholdDigestPatchResponse = zDigestSetting;

export const zListHouseholdMembersV1HouseholdMembersGetResponse = z.array(zMemberResponse);

export const zRemoveHouseholdMemberV1HouseholdMembersMembershipIdDeleteResponse = z.void();

export const zChangeMemberRoleV1HouseholdMembersMembershipIdPatchResponse = zMemberResponse;

export const zLeaveHouseholdV1HouseholdLeavePostResponse = z.void();

export const zDissolvePreviewV1HouseholdDissolvePreviewGetResponse = zDissolvePreview;

export const zDissolveHouseholdV1HouseholdDissolvePostResponse = z.void();

export const zCreateHouseholdChildV1HouseholdChildrenPostResponse = zChildResponse;

export const zListRecipesV1RecipesGetResponse = z.array(zRecipeSummary);

export const zCreateRecipeV1RecipesPostResponse = zRecipeResponse;

export const zImportRecipeV1RecipesImportPostResponse = zRecipeImportResponse;

export const zDeleteRecipeV1RecipesRecipeIdDeleteResponse = z.void();

export const zGetRecipeV1RecipesRecipeIdGetResponse = zRecipeResponse;

export const zUpdateRecipeV1RecipesRecipeIdPatchResponse = zRecipeResponse;

export const zRecipeNutritionV1RecipesRecipeIdNutritionGetResponse = zNutritionOut;

export const zDeleteRecipePhotoV1RecipesRecipeIdPhotoDeleteResponse = z.void();

export const zSetRecipePhotoV1RecipesRecipeIdPhotoPutResponse = zRecipeResponse;

export const zListIngredientsV1IngredientsGetResponse = z.array(zIngredientOut);

export const zSyncBatchV1SyncShoppingBatchPostResponse = zSyncBatchResponse;

export const zSyncPullV1SyncShoppingGetResponse = zSyncPullResponse;

export const zListTemplatesV1TasksTemplatesGetResponse = z.array(zTaskTemplateSummary);

export const zCreateTemplateV1TasksTemplatesPostResponse = zTaskTemplateResponse;

export const zDeleteTemplateV1TasksTemplatesTemplateIdDeleteResponse = z.void();

export const zGetTemplateV1TasksTemplatesTemplateIdGetResponse = zTaskTemplateResponse;

export const zUpdateTemplateV1TasksTemplatesTemplateIdPatchResponse = zTaskTemplateResponse;

export const zListInstancesV1TasksInstancesGetResponse = z.array(zTaskInstanceResponse);

export const zCreateInstanceV1TasksInstancesPostResponse = zTaskInstanceResponse;

export const zGetInstanceV1TasksInstancesInstanceIdGetResponse = zTaskInstanceResponse;

export const zCompleteInstanceV1TasksInstancesInstanceIdCompletePostResponse = zTaskInstanceResponse;

export const zRoomHeatmapV1TasksHeatmapGetResponse = z.array(zRoomHeatmapEntry);

export const zListRoomsV1TasksRoomsGetResponse = z.array(zRoomResponse);

export const zCreateRoomV1TasksRoomsPostResponse = zRoomResponse;

export const zDeleteRoomV1TasksRoomsRoomIdDeleteResponse = z.void();

export const zUpdateRoomV1TasksRoomsRoomIdPatchResponse = zRoomResponse;

export const zMyBalanceV1EconomyBalanceGetResponse = zBalanceResponse;

export const zMyLedgerV1EconomyLedgerGetResponse = z.array(zLedgerEntryResponse);

export const zPostCorrectionV1EconomyCorrectionsPostResponse = zBalanceResponse;

export const zListRewardsV1EconomyRewardsGetResponse = z.array(zRewardResponse);

export const zCreateRewardV1EconomyRewardsPostResponse = zRewardResponse;

export const zDeleteRewardV1EconomyRewardsRewardIdDeleteResponse = z.void();

export const zGetRewardV1EconomyRewardsRewardIdGetResponse = zRewardResponse;

export const zUpdateRewardV1EconomyRewardsRewardIdPatchResponse = zRewardResponse;

export const zRedeemRewardV1EconomyRewardsRewardIdRedeemPostResponse = zRedemptionResponse;

export const zListRedemptionsV1EconomyRedemptionsGetResponse = z.array(zRedemptionResponse);

export const zFulfillRedemptionV1EconomyRedemptionsRedemptionIdFulfillPostResponse = zRedemptionResponse;

export const zSendThanksV1EconomyThanksPostResponse = zThanksResponse;

export const zWeeklyChallengeV1EconomyChallengeGetResponse = zChallengeResponse;

export const zFairnessV1EconomyFairnessGetResponse = zFairnessResponse;

export const zListListingsV1MarketplaceListingsGetResponse = z.array(zListingResponse);

export const zCreateListingV1MarketplaceListingsPostResponse = zListingResponse;

export const zAcceptListingV1MarketplaceListingsListingIdAcceptPostResponse = zListingResponse;

export const zWithdrawListingV1MarketplaceListingsListingIdWithdrawPostResponse = zListingResponse;

export const zSettleListingV1MarketplaceListingsListingIdSettlePostResponse = zListingResponse;

export const zListRulesV1MarketplaceAutoAcceptGetResponse = z.array(zAutoAcceptRuleResponse);

export const zCreateRuleV1MarketplaceAutoAcceptPostResponse = zAutoAcceptRuleResponse;

export const zDeleteRuleV1MarketplaceAutoAcceptRuleIdDeleteResponse = z.void();

export const zCreateCaptureV1CapturePostResponse = zCaptureResponse;

export const zListInboxV1CaptureInboxGetResponse = z.array(zCaptureResponse);

export const zConfirmCaptureV1CaptureCaptureIdConfirmPostResponse = zCaptureResponse;

export const zDismissCaptureV1CaptureCaptureIdDismissPostResponse = zCaptureResponse;

export const zListEventsV1CalendarEventsGetResponse = z.array(zEventResponse);

export const zCreateEventV1CalendarEventsPostResponse = zEventResponse;

export const zDeleteEventV1CalendarEventsEventIdDeleteResponse = z.void();

export const zGetEventV1CalendarEventsEventIdGetResponse = zEventResponse;

export const zUpdateEventV1CalendarEventsEventIdPatchResponse = zEventResponse;

export const zCancelOccurrenceV1CalendarEventsEventIdCancelOccurrencePostResponse = zEventResponse;

export const zRestoreOccurrenceV1CalendarEventsEventIdRestoreOccurrencePostResponse = zEventResponse;

export const zMoveOccurrenceV1CalendarEventsEventIdMoveOccurrencePostResponse = zEventResponse;

export const zResetOccurrenceV1CalendarEventsEventIdResetOccurrencePostResponse = zEventResponse;

export const zImportIcsV1CalendarImportPostResponse = zIcsImportResult;

export const zDeleteFeedV1CalendarFeedDeleteResponse = z.void();

export const zCreateFeedV1CalendarFeedPostResponse = zFeedResponse;

export const zListSubscriptionsV1CalendarSubscriptionsGetResponse = z.array(zSubscriptionResponse);

export const zCreateSubscriptionV1CalendarSubscriptionsPostResponse = zSubscriptionResponse;

export const zDeleteSubscriptionV1CalendarSubscriptionsSubscriptionIdDeleteResponse = z.void();

export const zGetSubscriptionV1CalendarSubscriptionsSubscriptionIdGetResponse = zSubscriptionResponse;

export const zUpdateSubscriptionV1CalendarSubscriptionsSubscriptionIdPatchResponse = zSubscriptionResponse;

export const zCheckSubscriptionV1CalendarSubscriptionsSubscriptionIdCheckPostResponse = zSubscriptionCheckResponse;

export const zGetWeatherV1WeatherGetResponse = zWeatherResponse;

export const zGeocodeV1WeatherGeocodeGetResponse = z.array(zGeocodeResult);

export const zDeleteLocationV1WeatherLocationDeleteResponse = z.void();

export const zPutLocationV1WeatherLocationPutResponse = zLocationResponse;

export const zSuggestSlotsV1SchedulingSlotsGetResponse = z.array(zSlotResponse);

export const zGetWeekV1MealplanGetResponse = zWeekResponse;

export const zClearSlotV1MealplanSlotDeleteResponse = zWeekResponse;

export const zSetSlotV1MealplanSlotPutResponse = zWeekResponse;

export const zMarkCookedV1MealplanSlotCookedPostResponse = z.void();

export const zPersonalSuggestionV1MealplanSuggestionGetResponse = zPersonalSuggestionResponse;

export const zSuggestSlotV1MealplanSuggestPostResponse = zWeekResponse;

export const zSuggestWeekV1MealplanSuggestWeekPostResponse = zWeekResponse;

export const zCopyWeekV1MealplanCopyPostResponse = zWeekResponse;

export const zCreateCookTaskV1MealplanSlotCookTaskPostResponse = zCookTaskResult;

export const zCreatePrepTaskV1MealplanSlotPrepTaskPostResponse = zPrepTaskResult;

export const zWeekNutritionV1MealplanNutritionGetResponse = zWeekNutrition;

export const zToShoppingV1MealplanToShoppingPostResponse = zGenerateResult;

export const zListNotesV1NotesGetResponse = z.array(zNoteSummary);

export const zCreateNoteV1NotesPostResponse = zNoteResponse;

export const zListTrashV1NotesTrashGetResponse = z.array(zTrashedNote);

export const zDeleteNoteV1NotesNoteIdDeleteResponse = z.void();

export const zGetNoteV1NotesNoteIdGetResponse = zNoteResponse;

export const zUpdateNoteV1NotesNoteIdPatchResponse = zNoteResponse;

export const zListVersionsV1NotesNoteIdVersionsGetResponse = z.array(zNoteVersionResponse);

export const zRestoreVersionV1NotesNoteIdRestorePostResponse = zNoteResponse;

export const zUntrashNoteV1NotesNoteIdUntrashPostResponse = zNoteResponse;

export const zConvertToTaskV1NotesNoteIdToTaskPostResponse = zToTaskResult;

export const zListInboxV1LettersGetResponse = z.array(zLetterSummary);

export const zCreateLetterV1LettersPostResponse = zLetterResponse;

export const zUnreadCountV1LettersUnreadCountGetResponse = zUnreadCount;

export const zGetLetterV1LettersLetterIdGetResponse = zLetterResponse;

export const zConvertToTaskV1LettersLetterIdToTaskPostResponse = zLetterToTaskResult;

export const zListGuidesV1GuidesGetResponse = z.array(zGuideSummary);

export const zCreateGuideV1GuidesPostResponse = zGuideResponse;

export const zDeleteGuideV1GuidesGuideIdDeleteResponse = z.void();

export const zGetGuideV1GuidesGuideIdGetResponse = zGuideResponse;

export const zUpdateGuideV1GuidesGuideIdPatchResponse = zGuideResponse;

export const zListAttachmentsV1GuidesGuideIdAttachmentsGetResponse = z.array(zAttachmentResponse);

export const zUploadAttachmentV1GuidesGuideIdAttachmentsPostResponse = zAttachmentResponse;

export const zDeleteAttachmentV1GuidesGuideIdAttachmentsAttachmentIdDeleteResponse = z.void();

export const zListCommentsV1CommentsGetResponse = z.array(zCommentResponse);

export const zCreateCommentV1CommentsPostResponse = zCommentResponse;

export const zDeleteCommentV1CommentsCommentIdDeleteResponse = z.void();

export const zUpdateCommentV1CommentsCommentIdPatchResponse = zCommentResponse;

export const zListLinksV1LinksGetResponse = z.array(zLinkResponse);

export const zCreateLinkV1LinksPostResponse = zLinkResponse;

export const zDeleteLinkV1LinksLinkIdDeleteResponse = z.void();

export const zListKeysV1VaultKeysGetResponse = z.array(zEnvelopeResponse);

export const zPutKeyV1VaultKeysPutResponse = zEnvelopeResponse;

export const zListItemsV1VaultItemsGetResponse = z.array(zVaultItemSummary);

export const zCreateItemV1VaultItemsPostResponse = zVaultItemResponse;

export const zDeleteItemV1VaultItemsItemIdDeleteResponse = z.void();

export const zGetItemV1VaultItemsItemIdGetResponse = zVaultItemResponse;

export const zUpdateItemV1VaultItemsItemIdPatchResponse = zVaultItemResponse;

export const zListConnectionsV1WearablesConnectionsGetResponse = z.array(zConnectionResponse);

export const zAuthorizeV1WearablesOuraAuthorizePostResponse = zAuthorizeResponse;

export const zUpdateConsentsV1WearablesConnectionsConnectionIdConsentsPatchResponse = z.union([
    zConnectionResponse,
    z.null()
]);

export const zDeleteConnectionV1WearablesConnectionsConnectionIdDeleteResponse = z.void();

export const zListFeedbackV1FeedbackGetResponse = z.array(zFeedbackResponse);

export const zCreateFeedbackV1FeedbackPostResponse = zFeedbackResponse;

export const zLoginOpsAuthLoginPostResponse = zOperatorSession;

export const zLogoutOpsAuthLogoutPostResponse = z.void();

export const zMeOpsMeGetResponse = zOperatorMe;

export const zHealthOpsHealthGetResponse = zOpsHealth;

export const zKpisOpsKpisGetResponse = zOpsKpis;

export const zListBannersOpsBannersGetResponse = z.array(zBannerResponse);

export const zCreateBannerOpsBannersPostResponse = zBannerResponse;

export const zDeactivateBannerOpsBannersBannerIdDeactivatePostResponse = zBannerResponse;

export const zGetFlagsOpsFlagsGetResponse = zOpsFlags;

export const zSetFlagOpsFlagsKeyPutResponse = zOpsFlags;

export const zSearchHouseholdsOpsHouseholdsGetResponse = z.array(zHouseholdMetadata);

export const zHouseholdDetailOpsHouseholdsHouseholdIdGetResponse = zHouseholdMetadata;

export const zListFeedbackOpsFeedbackGetResponse = z.array(zOpsFeedbackEntry);

export const zListAuditOpsAuditGetResponse = z.array(zAuditLogEntry);

export const zListOperatorsOpsOperatorsGetResponse = z.array(zOperatorSummary);

export const zDeactivateOperatorOpsOperatorsOperatorIdDeactivatePostResponse = zOperatorSummary;

export const zReactivateOperatorOpsOperatorsOperatorIdReactivatePostResponse = zOperatorSummary;

export const zOpsPasskeyRegisterBeginOpsAuthPasskeysRegisterBeginPostResponse = zOpsPasskeyOptions;

export const zOpsPasskeyRegisterCompleteOpsAuthPasskeysRegisterCompletePostResponse = z.void();

export const zOpsPasskeyLoginBeginOpsAuthPasskeysLoginBeginPostResponse = zOpsPasskeyLoginOptions;

export const zOpsPasskeyLoginCompleteOpsAuthPasskeysLoginCompletePostResponse = zOperatorSession;

export const zOpsListPasskeysOpsPasskeysGetResponse = z.array(zOperatorPasskeySummary);

export const zOpsDeletePasskeyOpsPasskeysPasskeyIdDeleteResponse = z.void();

export const zActiveBannersV1BannersGetResponse = z.array(zBannerResponse);