// Stub for virtual:pwa-register/react (wired via resolve.alias in vitest.config.ts): the real
// module is generated by vite-plugin-pwa inside the Vite build and does not exist under vitest.
type Setter = (value: boolean) => void;

export function useRegisterSW(): {
  needRefresh: [boolean, Setter];
  offlineReady: [boolean, Setter];
  updateServiceWorker: (reloadPage?: boolean) => Promise<void>;
} {
  return {
    needRefresh: [false, () => undefined],
    offlineReady: [false, () => undefined],
    updateServiceWorker: async () => undefined,
  };
}
